name: Unit and E2E tests

on:
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: pnpm install and test
        run: |
          pnpm install --frozen-lockfile
          pnpm test
  e2e-chrome:
    name: e2e chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v7
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: pnpm

      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v7
        with:
          command: pnpm e2e:ci
